### ISSUE TITLE
Import linuxaudio wiki soundfonts list

### ISSUE THREAD

**Issue by nodiscc** [lfzawacki/musical-artifacts#10]
examine/copy http://wiki.linuxaudio.org/wiki/soundfont_collection to musical-artifacts

**Comment by lfzawacki** [comment]
At some point I'll get to some of that myself. One thing to note about adding these files (and all the other ones in the issue section) is that it would be nice to have a description and good tagging and this requires people who are familiar with the files and sounds themselves so reaching out to other community members could make thing easier.

As a reminder to you and everyone reading this, I'm making an informal list of such free/libre files here under the section 'Potential Artifacts' https://trello.com/b/ExTElvLv/musical-artifacts . Also thanks for your help with the project, I'll have more time to dedicate to it in the coming weeks.

**Comment by lfzawacki** [comment]
... and also while doing this we should take the chance to merge the soundfont page into this one http://wiki.linuxaudio.org/wiki/free_audio_data

**Comment by nodiscc** [comment]
Stale issue, cleaning up.
