### ISSUE TITLE
show the date an item was uploaded / updated / created

### ISSUE THREAD

**Issue by wolftune** [lfzawacki/musical-artifacts#12]
It's nice to sort by date, but I don't see a way to show what those dates actually are. The ideal would be to log when I last logged in / visited and then identify for me what's new.

**Comment by lfzawacki** [comment]
As of commit ![24d867](https://github.com/lfzawacki/musical-artifacts/commit/24d8675091d2f9b01b78a2d9637d51d67a1c6c50) and ![ba56f2](https://github.com/lfzawacki/musical-artifacts/commit/ba56f2ec51a84deda612c45ad514ff8fcd598697) I tweaked the design of the artifact page a little to express the uploaded and updated dates next to the title and author name.

Also the time you last logged in will be used to generate a little ribbon next to the new artifacts. Here's an example of how it looks:

![selection_082](https://cloud.githubusercontent.com/assets/33211/12057439/00e5d012-af0f-11e5-8e05-b7cd12d26c3d.jpg)

I you feel there's something missing for this issue feel free to reopen.

**Comment by wolftune** [comment]
sweet! thanks!
