### ISSUE TITLE
License clarity, highlight licenses as free or non-free, and filter options…

### ISSUE THREAD

**Issue by wolftune** [lfzawacki/musical-artifacts#15]
The free licenses are the FSF-approved software one (like GPL), public domain, CC0, CC BY, and CC BY-SA.

Licenses like CC ones that have NC or ND terms are non-free.

Also, don't say "copyright" as a license term, everything that's not public domain or CC0 is copyrighted. The term you want is "All Rights Reserved" (which is, of course, non-free).

So, please mark the licenses that are non-free with a *non-free* indicator right where the licenses are mentioned for each item. Also, please separate the filter-by-license so that there's two sections for free and non-free, and offer a filter that will show only freely-licensed items (but will show *any* free license).

In general, people care most about this distinction, not about seeing all CC licenses at once (for example)

**Comment by lfzawacki** [comment]
Thanks, that makes sense. I'll get to it in the next fews days and keep you posted on this issue.

**Comment by lfzawacki** [comment]
Now every license is marked as being free/non-free and I've added a separator for free/non-free licenses in the edit/create form.

Since almost no one used different licenses as a filter to browse artifacts I just went ahead with your advice and now there's a 'Only show freely licensed' and 'Show with all licenses' link next to the tags in the filtering area.

I call copyright 'All Rights Reserved' now too.

I'm still trying things around so further feedback is welcome.

**Comment by wolftune** [comment]
Good work! Thanks!

I'd change "Licensed as..." to "Filter by license:"

I'd like to see a mark on the listing of each non-free item that says "non-free" in a clear badge form that stands out enough to warn people.

**Comment by lfzawacki** [comment]
![selection_098](https://cloud.githubusercontent.com/assets/33211/13038473/87cc3d7a-d37a-11e5-9716-17b9e4975ae6.jpg)

![selection_097](https://cloud.githubusercontent.com/assets/33211/13038474/8ac1cd6a-d37a-11e5-9806-81d6ee6e2e92.jpg)

I've added this badge, linking to the FSF page on why the license is non free (or not in the case of 'All Rights Reserved' where it's kind of common knowledge). 

The design is getting a little cluttered, but this is good enough for me right now. I'm closing this, but feel free to further comment with suggestions.

**Comment by wolftune** [comment]
Looks great! There's always room for improvement, but this has the core important pieces in place now! Thanks :)
