### ISSUE TITLE
Fix erroneous CC license listings across site

### ISSUE THREAD

**Issue by wolftune** [lfzawacki/musical-artifacts#16]
1. There is no such thing as CC 4.0 Unported. All 4.0 licenses are "International" and don't need porting to different countries so have no such a thing as "unported"

2. It's not good, very confusing, to mark all CC licenses with just "Creative Commons 4.0". They *need* to have the full correct text title of the license *or* no written out text. It is wrong to spell out the license but only partially. I suggest keeping it spelled out, but it needs to be "Creative Commons Attribution Share-Alike 4.0 International" and "Creative Commons Attribution Non-Commercial Share-Alike 4.0 International" *or* "CC BY-SA 4.0 International" and "CC BY-NC-SA 4.0 International". In other words, if there is spelled out text, the NC license *must* have text that includes reference to NC and non-NC license lacking that text. It's not okay for the different licenses to have the same text with only the logo different.

Thanks

**Comment by lfzawacki** [comment]
Noted, I'll get to fixing this is a few days.

**Comment by lfzawacki** [comment]
Done, if you think there's no further improvements needed here feel free to close the issue.

**Comment by wolftune** [comment]
Good work. This is perfectly acceptable as is. However, to be picky, it is not common to spell out "Creative Commons" but keep the short "BY" in the same line. It's usually *all* short "CC BY" or all long ""Creative Commons Attribution 4.0 International". But it's perfectly clear and legal enough the way you have it, so if you prefer to keep it the way it is now, it's fine.
