### ISSUE TITLE
json format of artifacts

### ISSUE THREAD

**Issue by brummer10** [lfzawacki/musical-artifacts#25]
Hi

I've started to add a json parser to fetch the online guitarix-presets. First I download 
`GET https://musical-artifacts.com/artifacts.json?apps=guitarix >musical-artifacts.json`

then I parse the file, were I run into errors, related to the older guitarix presets.
They have token like this one:
`"mirrors":null`
were I end up with a error for reading the key_value.
It should be
`"mirrors":[]`

The first one with the null value is 
`"id":170,"name":"kokoko3k Guitarix Bank"`

do you see a way to correct that, or should I add a replace parser first, to read the json file?

kind regards
hermann

**Comment by lfzawacki** [comment]
If the file has no mirrors the json value should probably be an empty array and not null. This is something need to fix. I'll work on it and keep you updated. Thanks.

**Comment by lfzawacki** [comment]
This should be fixed, let me know if I can close the bug.

**Comment by brummer10** [comment]
Yes, works like a charm now. 
Thanks
