### ISSUE TITLE
Please provide a free-only Hydrogen feed

### ISSUE THREAD

**Issue by jonassmedegaard** [lfzawacki/musical-artifacts#26]
Hi,

Great service! The "Free licenses" option is much appreciated.

Please consider add a Hydrogen feed limited to only freely licensed works was offered.

Also, would be great to have clearly defined what exactly is meant by "Free licenses". Debian has one definition, FSF another, and numerous other organisations and individuals have yet other definitions.

**Comment by lfzawacki** [comment]
Thanks, sorry for such a delay answering this. I'll look into including filters into the hydrogen kits lists. The 'free license' definition is the FSF one unless I'm remembering it incorrectly.

**Comment by lfzawacki** [comment]
Implemented something that should provide what you need: https://github.com/lfzawacki/musical-artifacts/wiki/Integrations#filtering-only-freely-licensed-files
