### ISSUE TITLE
Issue with a string translation

### ISSUE THREAD

**Issue by trebmuh** [lfzawacki/musical-artifacts#32]
Even if the string `CPU donation couldn't be loaded, consider unblocking it.` [is already translated in French](https://github.com/lfzawacki/musical-artifacts/blob/master/config/locales/fr.yml#L376), it is showed in English and not in French on the website:

![musicalartifacts](https://user-images.githubusercontent.com/8705846/38244474-1a219e7e-373b-11e8-8991-b08716a53113.png)

**Comment by lfzawacki** [comment]
Gonna look into this in the next few days.

**Comment by trebmuh** [comment]
Nice. Keep me in the loop.

**Comment by trebmuh** [comment]
@lfzawacki good eyes! My bad, sorry.
