### ISSUE TITLE
duplicate in wordings

### ISSUE THREAD

**Issue by trebmuh** [lfzawacki/musical-artifacts#42]
https://github.com/lfzawacki/musical-artifacts/blob/8efb56233e63f4cb828afc15673723c3a14ce5b3/config/locales/en.yml#L391

Isn't this "should survive termination shall survive termination" a copy/paste error?

From there: https://musical-artifacts.com/terms_and_conditions

**Comment by lfzawacki** [comment]
It's actually correct. Something like "aspects of this agreement that need to be kept after we break it by terminating the account will be kept".

**Comment by trebmuh** [comment]
OK
