### ISSUE TITLE
Add Bandshed Hydrogen drumkits

### ISSUE THREAD

**Issue by nodiscc** [lfzawacki/musical-artifacts#5]
Hydrogen: [Blackpearl4pc](http://www.bandshed.net/sounds/h2drumkit/AVLDrumkits-BlackPearl4pc.h2drumkit), [BlackPearl4pcAlt](http://www.bandshed.net/sounds/h2drumkit/AVLDrumkits-BlackPearl4pcAlternate.h2drumkit), [BlackPearl5pc](http://www.bandshed.net/sounds/h2drumkit/AVLDrumkits-BlackPearl5pc.h2drumkit), [RedZeppelin4pc](http://www.bandshed.net/sounds/h2drumkit/AVLDrumkits-RedZeppelin4pc.h2drumkit), [RedZeppelin5pc](http://www.bandshed.net/sounds/h2drumkit/AVLDrumkits-RedZeppelin5pc.h2drumkit), [Gimme a Hand](http://www.bandshed.net/sounds/h2drumkit/Gimme%20A%20Hand%201.0.h2drumkit)

**Comment by lfzawacki** [comment]
https://musical-artifacts.com/artifacts?tags=avl

Added.
