### ISSUE TITLE
Website isn’t working :(((

### ISSUE THREAD

**Issue by nadekomari** [lfzawacki/musical-artifacts#54]
Musical Artifacts isn’t working for me,it refuses to load and the rest of my websites do,did something happen or

**Comment by tvvoty** [comment]
I have this issue too. It does somewhat work through VPN for some reason, but still takes several minutes to load a page and hours so load a soundfont.

**Comment by lfzawacki** [comment]
Hello, there seems to be some problem with the website host. I'm investigating it.

**Comment by lfzawacki** [comment]
It should be up again now. The website was getting an unusual spike of traffic and I've limited it per user, the browsing and download speeds should be OK for now. Let me know if there's something else going on.

I'm not sure why some people may be having trouble acessing the website at all (maybe some DNS problem on Digital Ocean's side?). For example https://downforeveryoneorjustme.com/musical-artifacts.com?proto=https is returning 'down' for me, but the site is cleary working on my side.

**Comment by tvvoty** [comment]
Seems to be working more or less fine now, and without VPN.
