### ISSUE TITLE
[Bug] Certificate expired, cannot access site due to HSTS (Again) (also other bugs)

### ISSUE THREAD

**Issue by stgiga** [lfzawacki/musical-artifacts#74]
The site at the time of this issue is inaccessible due to an expired certificate and HSTS.

Please just disable HSTS permanently so we don't have THIS and #68 again. There's no credit-card stuff going on there.

 Oh, and while you're at it: some people have registered under their deadnames. Also, resetting passwords is quite difficult, and you can't reset your e-mail either. 
 
Also, certain SF2s require me to use SourceForge for hosting, which not all people do for some reason when making giant sf2s. This was not always the case. But considering the whole site is down...

**Comment by stgiga** [comment]
And it has happened again @lfzawacki

**Comment by stgiga** [comment]
Oh and by the way: My SF2s are available on my Archive.org account now too.

https://archive.org/details/stgigasoundfonts

**Comment by lfzawacki** [comment]
The site is no longer using HSTS
