### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by KoghaandSooga** [lfzawacki/musical-artifacts#76]
Click on the main site and nothing happens like it never got clicked on.  What's going on has the site finally been pulled? Shame yet even another part of the web ripped apart.

**Comment by trebmuh** [comment]
It is working here. Slowly, but working.

**Comment by Roph** [comment]
The site's getting painfully slow, makes me worry it's close to dying :(

**Comment by lfzawacki** [comment]
> The site's getting painfully slow, makes me worry it's close to dying :(

Last month we had some donations so I could focus time on beefing the CPU an RAM a little and working on optimizing the code and server settings to get the performance back to a good state. Currently I think it's at least usable. Sorry for the inconvenience.

**Comment by KoghaandSooga** [comment]
PS: Make sure that 'vintage' computer doesn't have 'Optiplex' in it's name or any kind of similar computer they have goofy things in their motherboards you will come to hate.
________________________________

**Comment by KoghaandSooga** [comment]
Sites that are computer music niche hobbies like this one (and others) will continue to die off sadly: because people on phones don't know nor care to know how do these kinds of hobby things, plus even if a phone could do these things it would be a lot more cumbersome requiring a lot more work arounds then when it was native back in the XP/Windows 7 era of sound cards.  Doing music stuff on a phone would essentially be a nightmare even on a high end 1,000$ + one!  at that price range just get yourself a @!#@ vintage XP/Windows era computer and slap Sound Blaster Audigy in! God you could do so much with those!

These phone 'users' only care about banking/social and shopping mostly social and shopping not necessarily in that particular order hence the word 'user' not creator.

This  mostly thanks to the push to phones only both by Google (TM) and Microsoft (TM) (which they fired a majority of their actual PC workers/tech staff during the development of windows 8 which is a big reason why it was such an atrocious mess)

Ironically Windows 8.1 actually attempted to fix some of it by letting you remove the crap that came on and adjust the looks but too little too late.

________________________________

**Comment by lfzawacki** [comment]
Closing
