### ISSUE TITLE
License for user contributions

### ISSUE THREAD

**Issue by nodiscc** [lfzawacki/musical-artifacts#8]
https://github.com/lfzawacki/musical-artifacts/wiki/Terms-and-Conditions is currently empty.

May I recommend the [Creative Commons Attribution Sharealike license](https://creativecommons.org/licenses/by-sa/4.0/) for user input on https://musical-artifacts.com/ ?

**Comment by lfzawacki** [comment]
I like the idea of CC-BY-SA for all the content on the site. I need help writing the terms and conditions page so I set up a draft page on the wiki where we can discuss this kind of thing, here it is:

https://github.com/lfzawacki/musical-artifacts/wiki/Terms-and-Conditions-%5BDraft%5D

**Comment by nodiscc** [comment]
updated the wiki page with suggestions

**Comment by lfzawacki** [comment]
Thanks for the help, I'm going to review a few other site's policies to write the rest of the document and it'll be up in a few days

**Comment by lfzawacki** [comment]
Update the wiki with a 'full' version of what a TOS might look like. I believe it covers the most important areas, but I can't say much about the language I've used. If anyone can help with some revisions here I'd be really grateful.

**Comment by lfzawacki** [comment]
Terms and conditions are now in place, the license for contributions is CC-BY-SA 4.0. Thanks for the help. https://github.com/lfzawacki/musical-artifacts/wiki/Terms-and-Conditions
